### ISSUE TITLE
IEEE Style Citations?

### ISSUE THREAD

**Issue by Sifor** [devinberg/ASEE-Conferences-Latex-Template#10]
The bib seems to be the wrong style, should be IEEE [1].

**Comment by Sifor** [comment]
Fixed changing line 13 to
``\usepackage[numbers,super]{natbib}"

For good measure, changing the call at the end of the document to 
``\bibliographystyle{IEEEtranN} "

**Comment by devinberg** [comment]
Interesting, I didn't catch that they had changed that. Thanks for noting it!
