### ISSUE TITLE
References not showing up

### ISSUE THREAD

**Issue by Sifor** [devinberg/ASEE-Conferences-Latex-Template#9]
Getting compiler error:
```
The style file: unsrtnat.bst
I found no \citation commands---while reading file main.aux
Database file #1: ASEEpaper.bib
```

**Comment by devinberg** [comment]
Could be if you have not cited anything in your document using the ```\cite{}``` command. If you have cited documents, you might need to delete your ```main.aux``` file and try compiling again.

Also, see [here](https://tex.stackexchange.com/questions/18045/problem-with-compiling-bibtex-no-citation-commands-error).

**Comment by devinberg** [comment]
If you still have trouble running it on your system, you could [try it on Overleaf](https://www.overleaf.com/latex/templates/asee-annual-conference-paper-template/hmpyrmqdrjgx) where it is known to work.

**Comment by Sifor** [comment]
I am using overleaf, thanks!
I think I had a broken section; it's fixed now.
